services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory
    ports:
      - "80:80"  # Expose port 80 of the container to port 80 on the host
