name: Deploy TRP-Loader-BS Site to Raspberry Pi

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Removing ssh-keyscan for now
    # - name: Add Raspberry Pi to known hosts
    #   run: ssh-keyscan -p ${{ secrets.RPI_PORT }} ${{ secrets.RPI_IP }} >> ~/.ssh/known_hosts

    - name: Verify SSH Connection
      run: |
        ssh -v -o StrictHostKeyChecking=no -p ${{ secrets.RPI_PORT }} ${{ secrets.RPI_USER }}@${{ secrets.RPI_IP }} 'echo "Connected successfully to Raspberry Pi"'

    - name: Deploy TRP-Loader-BS in Docker
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.RPI_PORT }} ${{ secrets.RPI_USER }}@${{ secrets.RPI_IP }} '
        cd /home/josh/trp-loader-bs &&
        git pull origin main &&
        docker-compose down &&
        docker-compose up -d --build
        '

    - name: Check Docker Containers
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.RPI_PORT }} ${{ secrets.RPI_USER }}@${{ secrets.RPI_IP }} '
        docker ps -a
        '
